### ISSUE TITLE
Hello, I'm interested in your work

### ISSUE THREAD

**Issue by Catosine** [wxh1996/SAP-EPIC#1]
I was wondering if it is possible for you to release your work.

Thank you!

**Comment by wxh1996** [comment]
Thanks for your interest. Please leave your email here. I'll send you the code and the pre-trained weights.

**Comment by Catosine** [comment]
Thank you @wxh1996 
My email is pengnan.fan@mail.mcgill.ca
:)

**Comment by wxh1996** [comment]
I have emailed the download link.
